# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UxLf5BJaQBbGnLwYkewxkToXyR7MyENn
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp


# =====================================================
# Physical constants
# =====================================================

G = 6.67430e-11          # m^3 kg^-1 s^-2
c = 299792458.0          # m/s
M_SUN = 1.98847e30       # kg


# =====================================================
# Equation of State
# Polytropic EOS:
#
# P = K * rho^gamma
#
# rho = rest-mass density
# =====================================================

K = 2.0e-2
GAMMA = 2.0


def density_from_pressure(P):
    """
    Return rest-mass density rho from pressure P.
    """

    return (P / K) ** (1.0 / GAMMA)


def energy_density(P):
    """
    Total energy density epsilon.

    epsilon = rho*c^2 + P/(gamma - 1)
    """

    rho = density_from_pressure(P)

    return rho * c**2 + P / (GAMMA - 1.0)


# =====================================================
# TOV equations
# =====================================================

def tov_equations(r, y):

    m, P = y

    # Outside the star
    if P <= 0:
        return [0.0, 0.0]

    epsilon = energy_density(P)

    compactness = 2 * G * m / (r * c**2)

    # Avoid numerical problems inside Schwarzschild radius
    if compactness >= 1.0:
        return [0.0, 0.0]

    # dm/dr
    dm_dr = (
        4 * np.pi * r**2 * epsilon / c**2
    )

    # dP/dr
    dP_dr = (
        -G
        * (epsilon + P)
        * (
            m
            + 4 * np.pi * r**3 * P / c**2
        )
        /
        (
            c**2
            * r**2
            * (1 - compactness)
        )
    )

    return [dm_dr, dP_dr]


# =====================================================
# Surface event
# Stop integration when P = 0
# =====================================================

def surface_event(r, y):

    return y[1]


surface_event.terminal = True
surface_event.direction = -1


# =====================================================
# Solve one neutron star
# =====================================================

def solve_star(central_pressure):

    # Start slightly away from r = 0
    r_start = 1.0

    # Maximum radius: 100 km
    r_end = 100000.0

    # Central density
    rho_c = density_from_pressure(central_pressure)

    # Small-radius approximation for enclosed mass
    initial_mass = (
        4.0
        * np.pi
        * r_start**3
        * rho_c
        / 3.0
    )

    initial_conditions = [
        initial_mass,
        central_pressure
    ]

    solution = solve_ivp(
        tov_equations,
        (r_start, r_end),
        initial_conditions,
        events=surface_event,
        max_step=100.0,
        rtol=1e-7,
        atol=[1e10, 1e23]
    )

    return solution


# =====================================================
# Mass-Radius calculation
# =====================================================

central_pressures = np.logspace(33, 36, 50)

radii = []
masses = []


for Pc in central_pressures:

    star = solve_star(Pc)

    # Check whether the surface was actually found
    if len(star.t_events[0]) == 0:
        print(
            "Warning: surface not found for Pc =",
            Pc
        )
        continue

    radius = star.t[-1]
    mass = star.y[0, -1]

    radii.append(radius / 1000.0)       # km
    masses.append(mass / M_SUN)         # solar masses


# =====================================================
# Results
# =====================================================

print("TOV Solver Completed")
print("--------------------")

print("Number of successful stars:", len(radii))

if len(masses) > 0:

    max_mass_index = np.argmax(masses)

    print(
        "Maximum mass =",
        masses[max_mass_index],
        "M_sun"
    )

    print(
        "Radius at maximum mass =",
        radii[max_mass_index],
        "km"
    )


# =====================================================
# Mass-Radius plot
# =====================================================

plt.figure(figsize=(8, 5))

plt.plot(
    radii,
    masses,
    marker="o",
    markersize=4
)

plt.xlabel("Radius (km)")
plt.ylabel("Mass (Solar Masses)")

plt.title("Mass-Radius Relation for Neutron Stars")

plt.grid()

plt.tight_layout()

plt.show()